SmartHome.Web/Controllers/RoleController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SmartHome.DomainCore.Data.Models;
using SmartHome.DomainCore.ServiceInterfaces.Permission;
using SmartHome.DomainCore.ServiceInterfaces.Role;
using SmartHome.Web.Models.Role;
using SmartHome.Web.Models.User;
using SmartHome.Web.Utils;
using Syncfusion.EJ2.Base;

namespace SmartHome.Web.Controllers
{
    [Authorize(Policy = "Administration.Role.View")]
    public class RoleController : Controller
    {
        private readonly ICreateRoleService createRoleService;
        private readonly IUpdateRoleService updateRoleService;
        private readonly IGetRolesService getRolesService;
        private readonly IGetPermissionsService getPermissionsService;

        public RoleController(
            ICreateRoleService createRoleService,
            IUpdateRoleService updateRoleService,
            IGetRolesService getRolesService,
            IGetPermissionsService getPermissionsService)
        {
            this.createRoleService = createRoleService;
            this.updateRoleService = updateRoleService;
            this.getRolesService = getRolesService;
            this.getPermissionsService = getPermissionsService;
        }

        [HttpGet]
        [Authorize(Policy = "Administration.Role.Edit")]
        public IActionResult Create()
        {
            return View("Create", new CreateRoleViewModel(new CreateRoleModel()));
        }
        
        [HttpPost]
        [Authorize(Policy = "Administration.Role.Edit")]
        public async Task<IActionResult> Create(CreateRoleModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await createRoleService.CreateRoleAsync(model);
                if (result.Succeeded)
                {
                    long roleId = (await getRolesService.GetRoleByNameAsync(model.Name!)).Id;
                    return RedirectToAction("Detail", new {id = roleId});
                }
                
                ModelState.AddValidationErrors(result);
            }

            return View("Create", new CreateRoleViewModel(model));
        }
        
        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            var role = await getRolesService.GetRoleByIdAsync(id);
            var permissions = await getPermissionsService.GetRolePermissionsAsync(id);

            return View("Detail", new DetailRoleViewModel(role, permissions));
        }
        
        [HttpPost]
        [Authorize(Policy = "Administration.Role.Edit")]
        public async Task<IActionResult> Update(RoleModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await updateRoleService.UpdateRoleAsync(model);
                if (result.Succeeded)
                {
                    return RedirectToAction("Detail", new {id = model.Id});
                }
                
                ModelState.AddValidationErrors(result);
            }

            var permissions = await getPermissionsService.GetRolePermissionsAsync(model.Id);
            return View("Detail", new DetailRoleViewModel(model, permissions));
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var roles = await getRolesService.GetAllRolesAsync();

            return View("List", new RoleListViewModel(roles));
        }
        
        [HttpGet]
        [Authorize(Policy = "Administration.Permission.View")]
        public async Task<IActionResult> PermissionsList(long roleId)
        {
            var vm = new RolePermissionsViewModel(roleId);
            vm.PermissionOptions = await getPermissionsService.GetAllPermissionsAsync();
            return View("PermissionsList", vm);
        }
        
        [Authorize(Policy = "Administration.Permission.View")]
        public async Task<IActionResult> PermissionsDataSource(long roleId, [FromBody]DataManagerRequest dm)
        {
            var result =
                await getPermissionsService.GetRolePermissionsAsync(roleId);
            return dm.RequiresCounts ? Json(new { result = result, count = result.Count }) : Json(result);
        }
        
        [Authorize(Policy = "Administration.Permission.View")]
        [Authorize(Policy = "Administration.Role.Edit")]
        public async Task<IActionResult> PermissionsUpdate(long roleId, [FromBody]CRUDModel batchModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            
            var removed =  batchModel.Deleted.Count > 0 ? batchModel.Deleted.Select(x => JsonConvert.DeserializeObject<PermissionModel>(x.ToString()))
                .Select(x => x.Id) : Enumerable.Empty<long>();
            var updated = batchModel.Changed.Count > 0 ? batchModel.Changed.Select(x => JsonConvert.DeserializeObject<PermissionModel>(x.ToString()))
                .Where(x => x.Name != null)
                .Select(x => (x.Id, x.Name!)) : Enumerable.Empty<ValueTuple<long, string>>();
            var added = batchModel.Added.Select(x => JsonConvert.DeserializeObject<PermissionModel>(x.ToString()))
                .Where(x => x.Name != null)
                .Select(x => x.Name!).ToList();

            var result = await updateRoleService.UpdatePermissionsAsync(roleId, removed, updated, added);
            if (!result.Succeeded)
            {
                return BadRequest(result.ToString());
            }
            
            
            var permissions =
                await getPermissionsService.GetRolePermissionsAsync(roleId);
            
            return Json(permissions);
        }
    }
}

SmartHome.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SmartHome.Common.Extensions;
using SmartHome.DomainCore.Data.Models;
using SmartHome.DomainCore.InfrastructureInterfaces;
using SmartHome.DomainCore.ServiceInterfaces.Permission;
using SmartHome.DomainCore.ServiceInterfaces.Role;
using SmartHome.DomainCore.ServiceInterfaces.User;
using SmartHome.Web.Models.Role;
using SmartHome.Web.Models.User;
using SmartHome.Web.Utils;
using Syncfusion.EJ2.Base;

namespace SmartHome.Web.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly ICreateUserService createUserService;
        private readonly IGetUsersService getUsersService;
        private readonly IUpdateUserService updateUserService;
        private readonly IDeleteUserService deleteUserService;
        private readonly IChangePasswordService changePasswordService;
        private readonly IGetRolesService getRolesService;
        private readonly IGetPermissionsService getPermissionsService;
        private readonly IPermissionVerificationService permissionVerificationService;

        public UserController(ICreateUserService createUserService, IGetUsersService getUsersService,
            IUpdateUserService updateUserService, IChangePasswordService changePasswordService,
            IGetRolesService getRolesService, IDeleteUserService deleteUserService,
            IGetPermissionsService getPermissionsService, IPermissionVerificationService permissionVerificationService)
        {
            this.createUserService = createUserService;
            this.getUsersService = getUsersService;
            this.updateUserService = updateUserService;
            this.changePasswordService = changePasswordService;
            this.getRolesService = getRolesService;
            this.deleteUserService = deleteUserService;
            this.getPermissionsService = getPermissionsService;
            this.permissionVerificationService = permissionVerificationService;
        }

        [HttpGet]
        public async Task<IActionResult> Detail(long id)
        {
            // isn't admin and he isn't trying to change his own password
            if (!await IsAuthorizedToChangeUserSettings(id))
            {
                return Unauthorized();
            }
            
            var model = await getUsersService.GetByIdAsync(id);

            var availableRoles = await getRolesService.GetAllRolesAsync();
            var userRoles = await getRolesService.GetUserRolesAsync(id);

            var permissions = await getPermissionsService.GetAllUserPermissionsWithRolesAsync(id);
            
            var viewModel = new DetailUserViewModel(model, userRoles.Select(x => x.Id).ToList(),
                (List<RoleModel>)availableRoles, (List<PermissionRoleModel>)permissions)
            {
                CanDelete = User.Identity.Name != model.UserName,
                CanEditRoles = await permissionVerificationService.HasPermissionAsync(User.Identity.Name!, "Administration.User.EditAll")
            };

            return View("Detail", viewModel);
        }
        
        [HttpPost]
        public async Task<IActionResult> Update(UserModel model, List<long> roles)
        {
            // isn't admin and he isn't trying to change his own password
            if (!await IsAuthorizedToChangeUserSettings(model.Id))
            {
                return Unauthorized();
            }
            
            if (ModelState.IsValid)
            {
                // if user attempts to update roles and is not admin => error
                var storedRoles = (await getRolesService.GetUserRolesAsync(model.Id)).Select(x => x.Id).ToList();
                if (!storedRoles.UnorderedEquals(roles) && !await permissionVerificationService.HasPermissionAsync(User.Identity.Name!, "Administration.User.EditAll"))
                {
                    return Unauthorized();
                }
                
                var result = await updateUserService.AddToOrRemoveFromRolesAsync(model.Id, roles);
                if (result.Succeeded)
                {
                    return RedirectToAction("Detail", new {id = model.Id});
                }
                
                ModelState.AddValidationErrors(result);
            }
            
            var availableRoles = await getRolesService.GetAllRolesAsync();
            var permissions = await getPermissionsService.GetAllUserPermissionsWithRolesAsync(model.Id);
            
            return View("Detail", new DetailUserViewModel(model, roles,
                (List<RoleModel>)availableRoles, (List<PermissionRoleModel>)permissions)
            {
                CanDelete = User.Identity.Name != model.UserName,
                CanEditRoles = await permissionVerificationService.HasPermissionAsync(User.Identity.Name!, "Administration.User.EditAll")
            });
        }

        [HttpGet]
        [Authorize(Policy = "Administration.User.ViewAll")]
        public async Task<IActionResult> List()
        {
            var users = await getUsersService.GetAllUsersAsync();

            return View("List", new UserListViewModel(users));
        }

        [HttpGet]
        [Authorize(Policy = "Administration.User.EditAll")]
        public IActionResult Create()
        {
            var viewModel = new CreateUserViewModel(new CreateUserModel());

            return View("Create", viewModel);
        }
        
        [HttpPost]
        [Authorize(Policy = "Administration.User.EditAll")]
        public async Task<IActionResult> Create(CreateUserModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await createUserService.CreateUserAsync(model);
                if (result.Succeeded)
                {
                    return RedirectToAction("Detail", new { id = (await getUsersService.GetByEmailAsync(model.Email!))!.Id });
                }
                
                ModelState.AddValidationErrors(result);
            }

            return View("Create", new CreateUserViewModel(model));
        }

        [HttpGet]
        [Authorize(Policy = "Administration.User.EditAll")]
        public async Task<IActionResult> Delete(long id)
        {
            // cannot delete your own account
            if ((await getUsersService.GetByNameAsync(User.Identity.Name!))?.Id == id)
            {
                return Unauthorized();
            }
            
            var result = await deleteUserService.DeleteUserAsync(id);

            if (result.Succeeded)
            {
                return RedirectToAction("List");
            }
            
            throw new ArgumentException("User cannot be deleted.");
        }

        [HttpGet]
        public async Task<IActionResult> ChangePassword(long id)
        {
            // isn't admin and he isn't trying to change his own password
            if (!await IsAuthorizedToChangeUserSettings(id))
            {
                return Unauthorized();
            }
            
            var model = await getUsersService.GetByIdAsync(id);
            
            var vm = new ChangePasswordViewModel(new ChangePasswordModel() { Id = model.Id });
            return View("ChangePassword", vm);
        }
        
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
        {
            // isn't admin and he isn't trying to change his own password
            if (!await IsAuthorizedToChangeUserSettings(model.Id))
            {
                return Unauthorized();
            }
            
            if (ModelState.IsValid)
            {
                var result = await changePasswordService.ChangePasswordAsync(model);

                if (result.Succeeded)
                {
                    return RedirectToAction("Detail", new {id = model.Id});
                }

                ModelState.AddValidationErrors(result);
            }

            return View("ChangePassword", new ChangePasswordViewModel(model));
        }

        [HttpGet]
        public async Task<IActionResult> PermissionsList(long userId)
        {
            if (!await IsAuthorizedToViewUserSettings(userId))
            {
                return Unauthorized();
            }
            
            var vm = new UserPermissionsViewModel(userId);
            vm.PermissionOptions = await getPermissionsService.GetAllPermissionsAsync();
            return View("PermissionsList", vm);
        }
        
        [Authorize(Policy = "Administration.User.ViewAll")]
        [Authorize(Policy = "Administration.Permission.View")]
        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> PermissionsDataSource(long userId, [FromBody]DataManagerRequest dm)
        {
            if (!await IsAuthorizedToViewUserSettings(userId))
            {
                return Unauthorized();
            }
            
            var result =
                await getPermissionsService.GetUserOnlyPermissionsAsync(userId);
            return dm.RequiresCounts ? Json(new { result = result, count = result.Count }) : Json(result);
        }
        
        [Authorize(Policy = "Administration.User.EditAll")]
        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> PermissionsUpdate(long userId, [FromBody]CRUDModel batchModel)
        {
            if (!await IsAuthorizedToChangeUserSettings(userId))
            {
                return Unauthorized();
            }
            
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            
            var removed =  batchModel.Deleted.Count > 0 ? batchModel.Deleted.Select(x => JsonConvert.DeserializeObject<PermissionModel>(x.ToString()))

SmartHome.Web/Views/Shared/Menu.cshtml
@using Syncfusion.EJ2.Navigations

<style>
    .menu>div:nth-child(2) {
        float: right;
    }
</style>

@{
    var leftMenuItems = new List<MenuItem>();
    leftMenuItems.Add(new MenuItem
    {
        Text = "Home",
        Url = Url.Action("Overview", "Home")
    });
    leftMenuItems.Add(new MenuItem()
    {
        Text = "Statistics"
    });

    if (User.Identity.IsAuthenticated)
    {
        leftMenuItems.Add(new MenuItem()
        {
            Text = "Files",
            Url = Url.Action("Files", "Home")
        });
    }
    leftMenuItems.Add(new MenuItem()
    {
        Text = "Enumerations",
        Items = new List<MenuItem>()
        {
            new MenuItem() { Text = "Places", Url = Url.Action("List", "Place") },
//            TODO
            new MenuItem() { Text = "Sensors", Url = Url.Action("Create", "Sensor")}
        }
    });
    leftMenuItems.Add(new MenuItem()
    {
        Text = "Administration",
        Items = new List<MenuItem>()
        {
            new MenuItem() { Text = "Users", Url = Url.Action("UserList", "User") },
            new MenuItem() { Text = "Roles", Url = Url.Action("RoleList", "Role") },
        }
    });

    var rightMenuItems = new List<MenuItem>();
    if (User.Identity.IsAuthenticated)
    {
        rightMenuItems.Add(new MenuItem()
        {
            Text = "Account",
            Items = new List<MenuItem>()
            {
                new MenuItem() {Text = "Settings", Url = Url.Action("Detail", "Account")},
                new MenuItem() {Text = "Log Out", Url = Url.Action("LogOut", "Account")}
            }
        });
    }
    else
    {
        rightMenuItems.Add(new MenuItem()
        {
            Text = "Log In",
            Url = Url.Action("Login", "Account")
        });
    }
}
<div class="menu-control menu small-hide">
    <ejs-menu id="main-menu-left" items="leftMenuItems" showItemOnClick="true"></ejs-menu>
    <ejs-menu id="main-menu-right" items="rightMenuItems" showItemOnClick="true"></ejs-menu>
</div>

@{
    var items = leftMenuItems.Concat(rightMenuItems).ToList();
}

<div class="menu-control menu small-show">
    <ejs-menu id="main-menu-left-hamburger" items="items" hamburgerMode="true" showItemOnClick="true"></ejs-menu>
</div>

SmartHome.Web/Views/Shared/_Layout.cshtml
@using Syncfusion.EJ2.Navigations
<!DOCTYPE html>

@* TODO: lang depends on country *@
<html lang="en">
<head>
    <environment names="Staging,Production">
        <link asp-href-include="~/lib/css/*.min.css" asp-href-exclude="~/lib/css/*-dark.min.css" rel="stylesheet"/>
        <link asp-href-include="~/out/css/*.min.css" asp-href-exclude="~/lib/css/*-dark.min.css" rel="stylesheet"/>
    </environment>
    <environment names="Development">
        <link asp-href-include="~/lib/css/*.css" asp-href-exclude="~/lib/css/*.min.css,~/lib/css/*-dark.css" rel="stylesheet"/>
        <link asp-href-include="~/css/global.css" rel="stylesheet"/>
        <link asp-href-include="~/css/*.css" asp-href-exclude="~/css/global.css,~/css/*-dark.css" rel="stylesheet"/>
    </environment>
    
    <environment names="Staging,Production">
         <script asp-src-include="~/lib/js/*.min.js" type="text/javascript"></script>
         <script asp-src-include="~/out/js/*.min.js" type="text/javascript"></script>
    </environment>
    <environment names="Development">
        <script asp-src-include="~/lib/js/*.js" asp-src-exclude="~/lib/js/*.min.js" type="text/javascript"></script>
        <script asp-src-include="~/lib/js/ej2.min.js" type="text/javascript"></script>
        <script asp-src-include="~/js/*.js" type="text/javascript"></script>
    </environment>
    
    <title>Smart home</title>
</head>
<body>
<nav><partial name="_Menu" /></nav>
<main>
    <h1>@ViewBag.Header</h1>
    @RenderBody()
</main>

<ejs-scripts></ejs-scripts>
</body>
</html>

SmartHome.Web/Views/Shared/_Menu.cshtml
@using SmartHome.DomainCore.Data.Models
@using Syncfusion.EJ2.Navigations
@inject SmartHome.DomainCore.ServiceInterfaces.Permission.IGetPermissionsService GetPermissionsService

@{
    bool isAuthenticated = User.Identity.IsAuthenticated;
    
    HashSet<string> userPermissions = isAuthenticated ?
        GetPermissionsService.GetAllUserPermissionsAsync(User.Identity.Name!)
            .Result.Select(x => x.Name!).ToHashSet() : new HashSet<string>();
}

@functions{
    private bool HasPermission(HashSet<string> userPermissions, string permissionName)
    {
        return userPermissions.Contains(permissionName);
    }
}

<style>
    .menu>div:nth-child(2) {
        float: right;
    }
</style>


@{
    
    var leftMenuItems = new List<MenuItem>();
    leftMenuItems.Add(new MenuItem
    {
        Text = "Home",
        Url = Url.Action("Overview", "Home")
    });
    if (isAuthenticated && HasPermission(userPermissions, "Statistic.View"))
    {
        leftMenuItems.Add(new MenuItem()
        {
            Text = "Statistics",
            Url = Url.Action("Index", "Statistics")
        });
    }

    if (isAuthenticated && HasPermission(userPermissions, "File.View"))
    {
        leftMenuItems.Add(new MenuItem()
        {
            Text = "Files",
            Url = Url.Action("Files", "Home")
        });
    }

    if (isAuthenticated && HasPermission(userPermissions, "Enumeration.View"))
    {
        var enumerations = new List<MenuItem>();
        if (HasPermission(userPermissions, "Enumeration.BatteryPowerSourceType.View"))
        {
            enumerations.Add(new MenuItem() {Text = "Battery power source types", Url = Url.Action("List", "BatteryPowerSourceType")});
        }
        if (HasPermission(userPermissions, "Enumeration.Place.View"))
        {
            enumerations.Add(new MenuItem() { Text = "Places", Url = Url.Action("List", "Place") });
        }
        if (HasPermission(userPermissions, "Enumeration.Sensor.View"))
        {
            enumerations.Add(new MenuItem() { Text = "Sensors", Url = Url.Action("List", "Sensor")});
        }
        if (HasPermission(userPermissions, "Enumeration.SensorType.View"))
        {
            enumerations.Add(new MenuItem() { Text = "Sensor types", Url = Url.Action("List", "SensorType") });
        }
        
        leftMenuItems.Add(new MenuItem()
        {
            Text = "Enumerations",
            Items = enumerations
        });
    }

    if (isAuthenticated && HasPermission(userPermissions, "Measurement.View"))
    {
        var measurements = new List<MenuItem>();
        if (HasPermission(userPermissions, "Measurement.Temperature.View"))
        {
            measurements.Add(new MenuItem() {Text = "Temperature", Url = Url.Action("List", "TemperatureMeasurement")});
        }

        leftMenuItems.Add(new MenuItem()
        {
            Text = "Measurements",
            Items = measurements
        });
    }
    if (isAuthenticated && HasPermission(userPermissions, "Administration.View"))
    {
        var administration = new List<MenuItem>();
        if (HasPermission(userPermissions, "Administration.User.ViewAll"))
        {
            administration.Add(new MenuItem() { Text = "Users", Url = Url.Action("List", "User") });
        }
        if (HasPermission(userPermissions, "Administration.Role.View"))
        {
            administration.Add(new MenuItem() { Text = "Roles", Url = Url.Action("List", "Role")});
        }
        if (HasPermission(userPermissions, "Administration.Permission.View"))
        {
            administration.Add(new MenuItem() { Text = "Permissions", Url = Url.Action("List", "Permission")});
        }

        leftMenuItems.Add(new MenuItem()
        {
            Text = "Administration",
            Items = administration
        });
    }

    var rightMenuItems = new List<MenuItem>();
    if (isAuthenticated)
    {
        rightMenuItems.Add(new MenuItem()
        {
            Text = "Account",
            Items = new List<MenuItem>()
            {
                new MenuItem() {Text = "Settings", Url = Url.Action("Detail", "Account")},
                new MenuItem() {Text = "Log Out", Url = Url.Action("LogOut", "Account")}
            }
        });
    }
    else
    {
        rightMenuItems.Add(new MenuItem()
        {
            Text = "Log In",
            Url = Url.Action("Login", "Account")
        });
    }
}
<div class="menu-control menu small-hide">
    <ejs-menu id="main-menu-left" items="leftMenuItems" showItemOnClick="true"></ejs-menu>
    <ejs-menu id="main-menu-right" items="rightMenuItems" showItemOnClick="true"></ejs-menu>
</div>

@{
    var items = leftMenuItems.Concat(rightMenuItems).ToList();
}

<div class="menu-control menu small-show">
    <ejs-menu id="main-menu-left-hamburger" items="items" hamburgerMode="true" showItemOnClick="true"></ejs-menu>
</div>